### ISSUE TITLE
SQLite3 error

### ISSUE THREAD

**Issue by patrick-armitage** [anicholson/barnabas#10] opened 2016-10-31 14:43 UTC
I'm getting this error running barnabas commands:

```
~ ᐅ barnabas list
unable to open database file (SQLite3::Exception)
[4339580434] *CallStack::unwind:Array(Pointer(Void)) +82
[4339580337] *CallStack#initialize:Array(Pointer(Void)) +17
[4339580296] *CallStack::new:CallStack +40
[4339549641] *raise<SQLite3::Exception>:NoReturn +25
[4339849892] *SQLite3::Connection#check<Int32>:Nil +36
[4339849640] *SQLite3::Connection#initialize<DB::Database>:Nil +120
[4339849499] *SQLite3::Connection::new<DB::Database>:SQLite3::Connection +123
[4339848980] *SQLite3::Driver#build_connection<DB::Database>:SQLite3::Connection +20
[4339549539] ~procProc(DB::Connection)@./libs/db/db/database.cr:39 +35
[4339841548] *DB::Pool(DB::Connection+)@DB::Pool(T)#build_resource:DB::Connection+ +60
[4339841426] *DB::Pool(DB::Connection+)@DB::Pool(T)#initialize<Int32, Int32, Int32, Float64, Int32, Float64, &Proc(DB::Connection+)>:Mutex +146
[4339835448] *DB::Pool(T)::new:initial_pool_size:max_pool_size:max_idle_pool_size:checkout_timeout:retry_attempts:retry_delay<Int32, Int32, Int32, Float64, Int32, Float64, &Proc(DB::Connection+)>:DB::Pool(DB::Con[4339835448] *DB::Pool(T)::new:initial_pool_size:max_pool_size:max_idle_pool_size:checkout_timeout:retry_attempts:retry_delay<Int32, Int32, Int32, Float64, Int32, Float64, &Proc(DB::Connection+)>:DB::Pool(DB::Connection+) +280
Unhandled exception in spawn:
end of file reached (IO::EOFError)
[4339580434] *CallStack::unwind:Array(Pointer(Void)) +82
[4339580337] *CallStack#initialize:Array(Pointer(Void)) +17
[4339580296] *CallStack::new:CallStack +40
[4339544473] *raise<IO::EOFError>:NoReturn +25
[4339682655] *IO::FileDescriptor+@IO#read_fully<Slice(UInt8)>:Int32 +111
[4339717316] *IO::ByteFormat::LittleEndian::decode<Int32:Class, IO::FileDescriptor+>:Int32 +68
[4339623618] *Int32@Int::from_io<IO::FileDescriptor+, IO::ByteFormat::LittleEndian:Module>:Int32 +34
[4339682530] *IO::FileDescriptor+@IO#read_bytes<Int32:Class>:Int32 +34
[4339712901] *Event::SignalHandler#run:NoReturn +53
[4339544316] ~procProc(Nil)@/usr/local/Cellar/crystal-lang/0.19.4_1/src/event/signal_handler.cr:93 +12
[4339573332] *Fiber#run:(IO::FileDescriptor | Nil) +164
[4339544297] ~proc2Proc(Fiber, (IO::FileDescriptor | Nil))@/usr/local/Cellar/crystal-lang/0.19.4_1/src/fiber.cr:29 +9
nection+) +280
[4339824620] *DB::Database#initialize<DB::Driver+, URI>:DB::Pool(DB::Connection+) +412
[4339824183] *DB::Database::new<DB::Driver+, URI>:DB::Database +151
[4339783643] *DB::build_database<URI>:DB::Database +43
[4339783585] *DB::build_database<String>:DB::Database +17
[4339809083] *RecipientRepository#load:Array(Recipient) +91
[4339808961] *RecipientRepository#all:Array(Recipient) +49
[4339550837] ~procProc(Array(String), RecipientRepository, Symbol)@./src/command/list.cr:2 +37
[4339792276] *Command::Base#process<Array(String), RecipientRepository>:Symbol +52
[4339488471] __crystal_main +2503
[4339545192] main +40
```

Fresh install with homebrew using OSX 10.11.16 and latest ZSH

**Comment by anicholson** [comment] 2016-11-01 20:26
@patrick-armitage sorry to hear that!

if you run `brew info barnabas`, which version does it tell you is installed?

**Comment by patrick-armitage** [comment] 2016-11-01 20:35
Thanks for following up on this!  `brew info barnabas` yields:

```
~ ᐅ brew info barnabas
anicholson/andrewdotnich/barnabas: stable 1, HEAD
Encourage your friends from your terminal
https://github.com/anicholson/barnabas
/usr/local/Cellar/barnabas/1 (7 files, 964.6K) *
  Built from source on 2016-10-31 at 09:37:29
From: https://github.com/anicholson/homebrew-andrewdotnich/blob/master/barnabas.rb
==> Dependencies
Required: crystal-lang ✔
```

**Comment by anicholson** [comment] 2016-11-01 21:11
@patrick-armitage I think I worked it out! Barnabas depends on SQLite, but I'd forgotten to flag it as an explicit dependency.

Could you please run `brew update`, then `brew install barnabas --HEAD` and see if you still get the error?

**Comment by patrick-armitage** [comment] 2016-11-02 14:25
@anicholson thanks, tried `brew install barnabas --HEAD` after uninstalling and now getting an SQLite3 error during install process:

```
~ ᐅ brew uninstall --force barnabas
Uninstalling barnabas... (7 files, 964.7K)
~ ᐅ brew install barnabas --HEAD
==> Installing barnabas from anicholson/andrewdotnich
==> Cloning https://github.com/anicholson/barnabas.git
Cloning into '/Users/patrick.armitage/Library/Caches/Homebrew/barnabas--git'...
remote: Counting objects: 254, done.
remote: Total 254 (delta 0), reused 0 (delta 0), pack-reused 254
Receiving objects: 100% (254/254), 35.28 KiB | 0 bytes/s, done.
Resolving deltas: 100% (151/151), done.
==> Checking out revision master
==> crystal deps update
==> crystal build src/barnabas.cr
==> crystal src/setup.cr
Last 15 lines from /Users/patrick.armitage/Library/Logs/Homebrew/barnabas/03.crystal:
[4393140068] *SQLite3::Connection#check<Int32>:Nil +36
[4393139816] *SQLite3::Connection#initialize<DB::Database>:Nil +120
[4393139675] *SQLite3::Connection::new<DB::Database>:SQLite3::Connection +123
[4393139540] *SQLite3::Driver#build_connection<DB::Database>:SQLite3::Connection +20
[4392992963] ~procProc(DB::Connection)@./libs/db/db/database.cr:39 +35
[4393135052] *DB::Pool(DB::Connection+)@DB::Pool(T)#build_resource:DB::Connection+ +60
[4393134930] *DB::Pool(DB::Connection+)@DB::Pool(T)#initialize<Int32, Int32, Int32, Float64, Int32, Float64, &Proc(DB::Connection+)>:Mutex +146
[4393130008] *DB::Pool(T)::new:initial_pool_size:max_pool_size:max_idle_pool_size:checkout_timeout:retry_attempts:retry_delay<Int32, Int32, Int32, Float64, Int32, Float64, &Proc(DB::Connection+)>:DB::Pool(DB::Connection+) +280
[4393122140] *DB::Database#initialize<DB::Driver+, URI>:DB::Pool(DB::Connection+) +412
[4393121703] *DB::Database::new<DB::Driver+, URI>:DB::Database +151
[4393095051] *DB::build_database<URI>:DB::Database +43
[4393094993] *DB::build_database<String>:DB::Database +17
[4393112820] *RecipientRepository#create:DB::ExecResult +68
[4392934762] __crystal_main +1866
[4392990984] main +40

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/anicholson/homebrew-andrewdotnich/issues
```

**Comment by anicholson** [comment] 2016-11-03 10:38
@patrick-armitage I was able to reproduce the error you just saw, and pushed a fix. Can you try again, please? :)

**Comment by patrick-armitage** [comment] 2016-11-03 14:46
@anicholson it installs without error now, so we are definitely making progress :)

```
~ ᐅ brew install barnabas --HEAD
==> Auto-updated Homebrew!
Updated 2 taps (anicholson/andrewdotnich, homebrew/core).
==> New Formulae
snap-telemetry
==> Updated Formulae
anicholson/andrewdotnich/barnabas         boost-build                               docker-swarm                              mercurial                                 s6
awscli                                    clib                                      freeipmi                                  mysql-sandbox                             sqlmap
bazel                                     convox                                    libvirt                                   roswell                                   zorba

==> Installing barnabas from anicholson/andrewdotnich
==> Cloning https://github.com/anicholson/barnabas.git
Updating /Users/patrick.armitage/Library/Caches/Homebrew/barnabas--git
==> Checking out revision master
==> crystal deps update
==> crystal build src/barnabas.cr
==> Installation complete!
==> Run 'barnabas setup' to get started
==> Shell integration
==>  If you use bash for your shell, add
==> source /usr/local/Cellar/barnabas/HEAD-b0e761c/share/suggest.bash
==> to your .bashrc file.
==> If you use ZSH instead, add
==> source /usr/local/Cellar/barnabas/HEAD-b0e761c/share/suggest.zsh
==> to your .zshrc file.
🍺  /usr/local/Cellar/barnabas/HEAD-b0e761c: 7 files, 979.3K, built in 4 seconds
~ ᐅ source /usr/local/Cellar/barnabas/HEAD-b0e761c/share/suggest.zsh
```

The problem seems to be, first, that the `barnabas setup` command brew asks me to run is not a valid command:

```
~ ᐅ barnabas setup
setup is not a valid command.
Known commands:
help            Print this help
add         Add a new contact to your list
list            List your contacts
send            Send a message
suggest         suggest someone to contact
```

And also, that it seems there's still an SQLite error when using other commands:

```
~ ᐅ barnabas list
unable to open database file (SQLite3::Exception)
[4429549826] *CallStack::unwind:Array(Pointer(Void)) +82
[4429549729] *CallStack#initialize:Array(Pointer(Void)) +17
[4429549688] *CallStack::new:CallStack +40
[4429516761] *raise<SQLite3::Exception>:NoReturn +25
[4429819940] *SQLite3::Connection#check<Int32>:Nil +36
[4429819688] *SQLite3::Connection#initialize<DB::Database>:Nil +120
[4429819547] *SQLite3::Connection::new<DB::Database>:SQLite3::Connection +123
[4429819028] *SQLite3::Driver#build_connection<DB::Database>:SQLite3::Connection +20
[4429516659] ~procProc(DB::Connection)@./libs/db/db/database.cr:39 +35
[4429811596] *DB::Pool(DB::Connection+)@DB::Pool(T)#build_resource:DB::Connection+ +60
[4429811474] *DB::Pool(DB::Connection+)@DB::Pool(T)#initialize<Int32, Int32, Int32, Float64, Int32, Float64, &Proc(DB::Connection+)>:Mutex +146
[4429805496] *DB::Pool(T)::new:initial_pool_size:max_pool_size:max_idle_pool_size:checkout_timeout:retry_attempts:retry_delay<Int32, Int32, Int32, Float64, Int32, Float64, &Proc(DB::Connection+)>:DB::Pool(DB::Con[4429805496] *DB::Pool(T)::new:initial_pool_size:max_pool_size:max_idle_pool_size:checkout_timeout:retry_attempts:retry_delay<Int32, Int32, Int32, Float64, Int32, Float64, &Proc(DB::Connection+)>:DB::Pool(DB::Connection+) +280
Unhandled exception in spawn:
end of file reached (IO::EOFError)
[4429549826] *CallStack::unwind:Array(Pointer(Void)) +82
[4429549729] *CallStack#initialize:Array(Pointer(Void)) +17
[4429549688] *CallStack::new:CallStack +40
[4429511593] *raise<IO::EOFError>:NoReturn +25
[4429652399] *IO::FileDescriptor+@IO#read_fully<Slice(UInt8)>:Int32 +111
[4429687060] *IO::ByteFormat::LittleEndian::decode<Int32:Class, IO::FileDescriptor+>:Int32 +68
[4429593234] *Int32@Int::from_io<IO::FileDescriptor+, IO::ByteFormat::LittleEndian:Module>:Int32 +34
[4429652274] *IO::FileDescriptor+@IO#read_bytes<Int32:Class>:Int32 +34
[4429682645] *Event::SignalHandler#run:NoReturn +53
[4429511436] ~procProc(Nil)@/usr/local/Cellar/crystal-lang/0.19.4_1/src/event/signal_handler.cr:93 +12
[4429542724] *Fiber#run:(IO::FileDescriptor | Nil) +164
[4429511417] ~proc2Proc(Fiber, (IO::FileDescriptor | Nil))@/usr/local/Cellar/crystal-lang/0.19.4_1/src/fiber.cr:29 +9
nection+) +280
[4429794668] *DB::Database#initialize<DB::Driver+, URI>:DB::Pool(DB::Connection+) +412
[4429794231] *DB::Database::new<DB::Driver+, URI>:DB::Database +151
[4429753403] *DB::build_database<URI>:DB::Database +43
[4429753345] *DB::build_database<String>:DB::Database +17
[4429779131] *RecipientRepository#load:Array(Recipient) +91
[4429779009] *RecipientRepository#all:Array(Recipient) +49
[4429517957] ~procProc(Array(String), RecipientRepository, Symbol)@./src/command/list.cr:2 +37
[4429762324] *Command::Base#process<Array(String), RecipientRepository>:Symbol +52
[4429455543] __crystal_main +2503
[4429512312] main +40
```

**Comment by anicholson** [comment] 2016-11-03 20:41
That's a strange error, because the update to the formula should have happened after I'd pushed the `setup` command!

I moved some of the setup actions the formula was doing into this `setup` command. Once that shows up in your list of commands, you should be good to go :)

I'm sure you have been, but have you been `brew update`ing between these? That might help if not.

Thanks for sticking with me while I work this out! @patrick-armitage :)

**Comment by patrick-armitage** [comment] 2016-11-04 18:02
Thanks @anicholson!  Hmmm you're right, that is weird.  I just ran `brew cleanup --force` which cleared out some previous barnabas installs, then `brew update`, then `brew install barnabas --HEAD`, and still no `setup` command exists.  I wonder why my formula won't update...  Maybe I need to remove and retap your repo?

**Comment by anicholson** [comment] 2016-11-05 02:55
@patrick-armitage that is odd! If you cd to `/usr/local/Cellar/barnabas`, find the git version, and do a manual `git pull`, that should punch it through.

**Comment by patrick-armitage** [comment] 2016-11-07 17:51
@anicholson i built from source and it works!  could not figure out how to git pull in brew cellar.  anyway, i'd say this one is resolved in master.  thanks!

**Closed as completed** 2016-11-07 17:56 UTC

**Comment by anicholson** [comment] 2016-11-07 22:32
Excellent! I'm glad :) 

Please let me know your experiences - feature requests, bug reports, etc.

:)
